name: eventbot
version: '1.0.0'
summary: EventBot is a local web app to hosts your pictures.
description: |
  EventBot allows everyone to share photos at an event, see photos in
  real-time and download in bulk without losing ownership or posting to
  social media.

grade: devel
confinement: devmode

apps:
  eventbot:
    command: eventbot

parts:
  eventbot:
# TODO how to replace with upstream path
#    source: https://github.com/mzzroboto/EventBot.git
    source: .
    source-branch: snap-package
    plugin: nodejs
